[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# We target the function that builds the UI for hovering over cards
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "local cfg = (card and card.ability) or _c['config']"
position = "after"
match_indent = true
payload = '''
-- Add the tooltip for Basic Joker Energy if the card is marked by it
if card and card.ability and card.ability.paperback_energized then
  info_queue[#info_queue + 1] = {
    set = 'Other',
    key = 'paperback_energized'
  }
end

-- Add tooltips for items removed from the pool by the paperback config
if card and card.config and card.config.center and card.config.center.paperback then
  local config = card.config.center.paperback

  for _, v in ipairs(config.requirements or {}) do
    if not PB_UTIL.config[v.setting] then
      info_queue[#info_queue + 1] = {
        set = v.set or 'Other',
        key = v.tooltip,
        vars = v.vars or {}
      }
    end
  end
end
'''
