[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.module]
source = "libs/nativefs.lua"
before = "main.lua"
name = "FP_nativefs"

[[patches]]
[patches.module]
source = "libs/json.lua"
before = "main.lua"
name = "FP_json"

[[patches]]
[patches.copy]
target = "main.lua"
position = "append"
sources = [
	"core/core.lua",
]

# Needed for SMODS compat
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = 'init_localization()'
position = "before"
payload = '''
if not (SMODS and SMODS.can_load) then FlowerPot.load_localization() end'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'engine/controller.lua'
pattern = "function Controller:key_press_update(key, dt)"
position = "after"
payload = '''
    if key == "escape" and G.ACTIVE_FLOWPOT_UI then
        G.FUNCS.exit_mods()
    end
'''
match_indent = true